// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cursor": {
    params: {};
  };
  "/claude-code": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/refund": {
    params: {};
  };
  "/og-image": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cursor" | "/claude-code" | "/dashboard" | "/terms" | "/privacy" | "/refund" | "/og-image" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/cursor.tsx": {
    id: "routes/cursor";
    page: "/cursor";
  };
  "routes/claude-code.tsx": {
    id: "routes/claude-code";
    page: "/claude-code";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/refund.tsx": {
    id: "routes/refund";
    page: "/refund";
  };
  "routes/og-image.tsx": {
    id: "routes/og-image";
    page: "/og-image";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/cursor": typeof import("./app/routes/cursor.tsx");
  "routes/claude-code": typeof import("./app/routes/claude-code.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/refund": typeof import("./app/routes/refund.tsx");
  "routes/og-image": typeof import("./app/routes/og-image.tsx");
  "routes/404": typeof import("./app/routes/404.tsx");
};